2024-02-22 15:40:11,047 - WARNING - The HTTP response timed out: https://www.n11.com/urun/samsung-ls24ag300nrxuf-24-1-ms-144-hz-full-hd-va-monitor-41068884?magaza=gamers-arena
2024-02-22 15:40:11,048 - INFO - Successfully fetched data from https://www.n11.com/urun/samsung-ls24ag300nrxuf-24-1-ms-144-hz-full-hd-va-monitor-41068884?magaza=gamers-arena
2024-02-22 15:40:36,777 - WARNING - The HTTP response timed out: https://www.n11.com/urun/sare-by-kasmir-hali-dijital-yikanabilir-kaymaz-amy-p-80x100-cm-21003034259-49175268?magaza=karacahome
2024-02-22 15:40:36,777 - INFO - Successfully fetched data from https://www.n11.com/urun/sare-by-kasmir-hali-dijital-yikanabilir-kaymaz-amy-p-80x100-cm-21003034259-49175268?magaza=karacahome
2024-02-22 15:40:53,279 - WARNING - The HTTP response timed out: https://www.n11.com/urun/karaca-pro-multimax-6-in-1-cok-amacli-mutfak-robotu-46083940?magaza=karacazuccaciye
2024-02-22 15:40:53,784 - INFO - Successfully fetched data from https://www.n11.com/urun/karaca-pro-multimax-6-in-1-cok-amacli-mutfak-robotu-46083940?magaza=karacazuccaciye
2024-02-22 15:41:33,862 - WARNING - The HTTP response timed out: https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:41:33,862 - INFO - Successfully fetched data from https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:43:15,411 - WARNING - The HTTP response timed out: https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:43:15,412 - INFO - Successfully fetched data from https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:43:24,803 - WARNING - The HTTP response timed out: https://www.n11.com/urun/karaca-pro-multimax-6-in-1-cok-amacli-mutfak-robotu-46083940?magaza=karacazuccaciye
2024-02-22 15:43:24,883 - INFO - Successfully fetched data from https://www.n11.com/urun/karaca-pro-multimax-6-in-1-cok-amacli-mutfak-robotu-46083940?magaza=karacazuccaciye
2024-02-22 15:43:37,194 - WARNING - The HTTP response timed out: https://www.n11.com/urun/karaca-pro-multimax-6-in-1-cok-amacli-mutfak-robotu-46083940?magaza=karacazuccaciye
2024-02-22 15:43:37,226 - INFO - Successfully fetched data from https://www.n11.com/urun/karaca-pro-multimax-6-in-1-cok-amacli-mutfak-robotu-46083940?magaza=karacazuccaciye
2024-02-22 15:44:54,100 - WARNING - The HTTP response timed out: https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:44:54,106 - INFO - Successfully fetched data from https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:45:10,515 - WARNING - The HTTP response timed out: https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:45:10,516 - INFO - Successfully fetched data from https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:46:23,610 - WARNING - The HTTP response timed out: https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:46:23,610 - INFO - Successfully fetched data from https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking
2024-02-22 15:46:58,974 - WARNING - The HTTP response timed out: https://www.n11.com/urun/porsima-0047-90-l-cift-gozlu-etiketli-camasir-sepeti-siyah-beyaz-46615753?magaza=turuncuelma43
2024-02-22 15:46:58,997 - INFO - Successfully fetched data from https://www.n11.com/urun/porsima-0047-90-l-cift-gozlu-etiketli-camasir-sepeti-siyah-beyaz-46615753?magaza=turuncuelma43
2024-02-22 15:49:57,685 - WARNING - The HTTP response timed out: https://www.n11.com/urun/porsima-0047-90-l-cift-gozlu-etiketli-camasir-sepeti-siyah-beyaz-46615753?magaza=turuncuelma43
2024-02-22 15:49:57,685 - INFO - Successfully fetched data from https://www.n11.com/urun/porsima-0047-90-l-cift-gozlu-etiketli-camasir-sepeti-siyah-beyaz-46615753?magaza=turuncuelma43
2024-02-22 15:51:46,800 - WARNING - The HTTP response timed out: https://www.n11.com/urun/porsima-0047-90-l-cift-gozlu-etiketli-camasir-sepeti-siyah-beyaz-46615753?magaza=turuncuelma43
2024-02-22 15:51:46,811 - INFO - Successfully fetched data from https://www.n11.com/urun/porsima-0047-90-l-cift-gozlu-etiketli-camasir-sepeti-siyah-beyaz-46615753?magaza=turuncuelma43
2024-02-22 15:54:30,938 - WARNING - The HTTP response timed out: https://www.n11.com/urun/porsima-0047-90-l-cift-gozlu-etiketli-camasir-sepeti-siyah-beyaz-46615753?magaza=turuncuelma43
2024-02-22 15:54:30,939 - INFO - Successfully fetched data from https://www.n11.com/urun/porsima-0047-90-l-cift-gozlu-etiketli-camasir-sepeti-siyah-beyaz-46615753?magaza=turuncuelma43
2024-02-22 15:57:06,258 - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\fehmi\Mindsite_Case\src\main.py", line 35, in main
    user_decision = input("\nDo you want to continue? (y/n):")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Varolan bir baðlantý uzaktaki bir ana bilgisayar tarafýndan zorla kapatýldý
2024-02-22 15:57:20,513 - WARNING - The HTTP response timed out: https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking,
2024-02-22 15:57:21,583 - INFO - Successfully fetched data from https://www.n11.com/urun/big-king-siyah-supersoft-triko-erkek-spor-ayakkabi-24171692?magaza=bigking,
2024-02-22 15:57:42,142 - WARNING - The HTTP response timed out: https://www.n11.com/urun/violet-90-litre-cift-gozlu-camasir-sepeti-gri-beyaz-5324327?magaza=turuncuelma43
2024-02-22 15:57:42,178 - INFO - Successfully fetched data from https://www.n11.com/urun/violet-90-litre-cift-gozlu-camasir-sepeti-gri-beyaz-5324327?magaza=turuncuelma43
2024-02-22 15:58:54,067 - WARNING - The HTTP response timed out: https://www.n11.com/urun/violet-90-litre-cift-gozlu-camasir-sepeti-gri-beyaz-5324327?magaza=turuncuelma43
2024-02-22 15:58:54,068 - INFO - Successfully fetched data from https://www.n11.com/urun/violet-90-litre-cift-gozlu-camasir-sepeti-gri-beyaz-5324327?magaza=turuncuelma43
2024-02-22 15:59:23,657 - WARNING - The HTTP response timed out: https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
2024-02-22 15:59:23,681 - INFO - Successfully fetched data from https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
2024-02-22 16:00:46,424 - WARNING - The HTTP response timed out: https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
2024-02-22 16:00:46,425 - INFO - Successfully fetched data from https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
2024-02-22 16:07:42,457 - WARNING - The HTTP response timed out: https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
2024-02-22 16:07:42,474 - INFO - Successfully fetched data from https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
2024-02-22 16:10:13,140 - WARNING - The HTTP response timed out: https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
2024-02-22 16:10:13,140 - INFO - Successfully fetched data from https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
2024-02-22 16:10:37,834 - WARNING - The HTTP response timed out: https://www.n11.com/urun/skechers-erkek-gri-spor-ayakkabi-894115tk-char-24334564?magaza=skechers
2024-02-22 16:10:37,855 - INFO - Successfully fetched data from https://www.n11.com/urun/skechers-erkek-gri-spor-ayakkabi-894115tk-char-24334564?magaza=skechers
2024-02-22 16:13:38,869 - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\fehmi\Mindsite_Case\src\main.py", line 35, in main
    user_decision = input("\nDo you want to continue? (y/n):")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\fehmi\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Varolan bir baðlantý uzaktaki bir ana bilgisayar tarafýndan zorla kapatýldý
2024-02-22 16:13:44,810 - WARNING - The HTTP response timed out: https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
2024-02-22 16:13:44,812 - INFO - Successfully fetched data from https://www.n11.com/urun/caterpillar-colorado-erkek-kahverengi-nubuk-bot-637-44545065?magaza=yesilkundura
